import type { Algorithm } from "./types.js";

export const ALGORITHMS: Algorithm[] = [
  {
    slug: "bro_id",
    idType: "BroId",
    description: "Custom binary ID for specific layouts or lengths",
    output: "binary",
    sortable: "no",
    coordination: "none",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "comb_guid",
    idType: "COMBGUID",
    description: "COMB GUID: UUID with time-ordered bytes for indexes",
    output: "uuid",
    sortable: "time",
    coordination: "none",
    jsSafe: true,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "cos_id",
    idType: "CosId",
    description: "Configurable CosId-style distributed ID",
    output: "long",
    sortable: "time",
    coordination: "worker",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "cuid_v1",
    idType: "CUIDv1",
    description: "Collision-resistant unique ID v1",
    output: "string",
    sortable: "no",
    coordination: "none",
    jsSafe: true,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "cuid_v2",
    idType: "CUIDv2",
    description: "Collision-resistant unique ID v2",
    output: "string",
    sortable: "no",
    coordination: "none",
    jsSafe: true,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "dts_id",
    idType: "DtsId",
    description: "Distributed time-service ID",
    output: "long",
    sortable: "time",
    coordination: "none",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "elastic_flake",
    idType: "ElasticFlake",
    description: "Snowflake variant tuned for Elasticsearch document IDs",
    output: "string",
    sortable: "time",
    coordination: "worker",
    jsSafe: true,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "flake",
    idType: "Flake",
    description: "Twitter Snowflake variant (time, machine, sequence)",
    output: "long",
    sortable: "time",
    coordination: "worker",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "flake_id",
    idType: "FlakeID",
    description: "Extended flake with extra custom bits",
    output: "long",
    sortable: "time",
    coordination: "worker",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "flex_id",
    idType: "FlexId",
    description: "Framework sequence-style ID",
    output: "long",
    sortable: "mono",
    coordination: "none",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "js_safety_id",
    idType: "JavaScriptSafetyId",
    description: "53-bit ID safe for JavaScript Number",
    output: "long",
    sortable: "time",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
  },
  {
    slug: "ksuid",
    idType: "KSUID",
    description: "K-sortable globally unique ID (Base62)",
    output: "string",
    sortable: "time",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
  },
  {
    slug: "lexical_uuid",
    idType: "LexicalUUID",
    description: "Lexicographically sortable UUID",
    output: "uuid",
    sortable: "lex",
    coordination: "none",
    jsSafe: true,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "mist_id",
    idType: "MIST_ID",
    description: "Increment + random; production increment must be shared",
    output: "long",
    sortable: "mono",
    coordination: "shared",
    jsSafe: false,
    localGenerate: true,
    localOnly: true,
  },
  {
    slug: "nano_id",
    idType: "NanoId",
    description: "Compact URL-safe unique string",
    output: "string",
    sortable: "no",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
  },
  {
    slug: "object_id",
    idType: "ObjectID",
    description: "Mongo-style 12-byte ObjectId (timestamp + random + counter)",
    output: "string",
    sortable: "time",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
  },
  {
    slug: "ordered_uuid",
    idType: "OrderedUuid",
    description: "Time-ordered UUID for index locality",
    output: "uuid",
    sortable: "time",
    coordination: "none",
    jsSafe: true,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "push_id",
    idType: "PushID",
    description: "Firebase-style chronological push ID",
    output: "string",
    sortable: "time",
    coordination: "none",
    jsSafe: true,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "atomic_id",
    idType: "RAtomicLong",
    description: "Shared atomic long sequence",
    output: "long",
    sortable: "mono",
    coordination: "shared",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "shared",
  },
  {
    slug: "rid",
    idType: "RID",
    description: "Shared generic ID",
    output: "string",
    sortable: "mono",
    coordination: "shared",
    jsSafe: true,
    localGenerate: false,
    generateBlockReason: "shared",
  },
  {
    slug: "segment_chain_id",
    idType: "SegmentChainId",
    description: "Segment-chain allocator",
    output: "long",
    sortable: "mono",
    coordination: "shared",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "shared",
  },
  {
    slug: "sid",
    idType: "SID",
    description: "Session-style ID (may embed expiry)",
    output: "string",
    sortable: "no",
    coordination: "none",
    jsSafe: true,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "sharding_id",
    idType: "ShardingID",
    description: "Shard-friendly distributed ID",
    output: "long",
    sortable: "time",
    coordination: "worker",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "snowflake",
    idType: "Snowflake",
    description: "Twitter Snowflake 64-bit (time, worker, sequence)",
    output: "long",
    sortable: "time",
    coordination: "worker",
    jsSafe: false,
    localGenerate: true,
  },
  {
    slug: "sonyflake",
    idType: "Sonyflake",
    description: "Sonyflake (10ms tick, 8-bit sequence, 16-bit machine)",
    output: "long",
    sortable: "time",
    coordination: "worker",
    jsSafe: false,
    localGenerate: true,
  },
  {
    slug: "business_id",
    idType: "TimeBasedBusinessId",
    description: "Time-based business ID",
    output: "long",
    sortable: "time",
    coordination: "none",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "entropy_id",
    idType: "TimeBasedEntropyId",
    description:
      "Original 64-bit ID: 32-bit seconds since epoch + 32-bit mixed entropy; no worker config",
    output: "long",
    sortable: "time",
    coordination: "none",
    jsSafe: false,
    localGenerate: true,
  },
  {
    slug: "tts_id",
    idType: "TtsId",
    description: "Timestamp + sequence ID",
    output: "long",
    sortable: "time",
    coordination: "none",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "ulid",
    idType: "ULID",
    description: "26-char Crockford Base32, lexicographically sortable",
    output: "string",
    sortable: "lex",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
  },
  {
    slug: "uuid_v1",
    idType: "UUIDv1",
    description: "UUID v1 (timestamp + node)",
    output: "uuid",
    sortable: "time",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
  },
  {
    slug: "uuid_v2",
    idType: "UUIDv2",
    description: "UUID v2 DCE security",
    output: "uuid",
    sortable: "time",
    coordination: "none",
    jsSafe: true,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "uuid_v3",
    idType: "UUIDv3",
    description: "UUID v3 name-based MD5 (discouraged)",
    output: "uuid",
    sortable: "no",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
    needsName: true,
  },
  {
    slug: "uuid_v4",
    idType: "UUIDv4",
    description: "UUID v4 random (poor default clustered PK)",
    output: "uuid",
    sortable: "no",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
  },
  {
    slug: "uuid_v5",
    idType: "UUIDv5",
    description: "UUID v5 name-based SHA-1",
    output: "uuid",
    sortable: "no",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
    needsName: true,
  },
  {
    slug: "uuid_v6",
    idType: "UUIDv6",
    description: "UUID v6 reordered Gregorian-time UUID",
    output: "uuid",
    sortable: "time",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
  },
  {
    slug: "uuid_v7",
    idType: "UUIDv7",
    description: "UUID v7 Unix-time ordered (recommended uncoordinated string)",
    output: "uuid",
    sortable: "time",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
  },
  {
    slug: "uuid_v8",
    idType: "UUIDv8",
    description: "UUID v8 custom; production node bits should be coordinated",
    output: "uuid",
    sortable: "time",
    coordination: "shared",
    jsSafe: true,
    localGenerate: true,
    localOnly: true,
  },
  {
    slug: "wx_seq",
    idType: "WxSeq",
    description: "WeChat-style sequence",
    output: "long",
    sortable: "mono",
    coordination: "none",
    jsSafe: false,
    localGenerate: false,
    generateBlockReason: "not_implemented",
  },
  {
    slug: "xid",
    idType: "XID",
    description: "Compact sortable globally unique ID",
    output: "string",
    sortable: "time",
    coordination: "none",
    jsSafe: true,
    localGenerate: true,
  },
];

const BY_SLUG = new Map(ALGORITHMS.map((a) => [a.slug, a]));

export function getAlgorithm(slug: string): Algorithm | undefined {
  return BY_SLUG.get(slug);
}

export function allSlugs(): string[] {
  return ALGORITHMS.map((a) => a.slug);
}

/** Slugs this MCP can sample-generate (aligned with the skill Python set). */
export function implementedSlugs(): string[] {
  return ALGORITHMS.filter((a) => a.localGenerate).map((a) => a.slug);
}

export function filterAlgorithms(opts: {
  coordination?: Algorithm["coordination"];
  output?: Algorithm["output"];
  sortable?: Algorithm["sortable"];
  jsSafe?: boolean;
  localGenerate?: boolean;
}): Algorithm[] {
  return ALGORITHMS.filter((a) => {
    if (opts.coordination && a.coordination !== opts.coordination) return false;
    if (opts.output && a.output !== opts.output) return false;
    if (opts.sortable && a.sortable !== opts.sortable) return false;
    if (opts.jsSafe !== undefined && a.jsSafe !== opts.jsSafe) return false;
    if (opts.localGenerate !== undefined && a.localGenerate !== opts.localGenerate) {
      return false;
    }
    return true;
  });
}
